#-------------------------------
# General Site Settings

title: David Wang
description: Powered by Jekyll and GitHub Pages
email: daviwang@seas.upenn.edu

menu:
- {name: 'Projects', url: ''}
# - {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
# - {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio for David Wang'
  rel-author: 'https://github.com/david-wang-1'
  rel-publisher: 'https://github.com/david-wang-1'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # About Me

  I'm pursuing a BSE in Computer Engineering and an MSE in Robotics at the University of Pennsylvania, with an anticipated graduation date of May 2019. I'm interested in software development, embedded systems, and firmware development, and am actively recruiting for Summer 2018 positions. Feel free to contact me at [daviwang@seas.upenn.edu](mailto:daviwang@seas.upenn.edu)!

contact: >
  # Contact

  You may contact me [through my email](mailto:daviwang@seas.upenn.edu) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Ghost Mouse', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/david-wang-1'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/david-wang-a4a856104/'}
- {icon: 'envelope', link: 'mailto:daviwang@seas.upenn.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
